config/routes.rb
Rails.application.routes.draw do

  get 'product/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/market'
  get 'static_pages/forum'
  get 'static_pages/contact'
  get 'us/new'
  get 'sessions/new'
 

  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/market' => 'static_pages#market'
  get '/forum' => 'static_pages#forum'
  get '/signup' => 'us#new'
  get    '/login'   => 'sessions#new'
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'
  get    '/upload'   => 'products#new'
  get '/products'=> 'products#index'
  post '/products'=> 'products#create'
  resources  :us
  resources :products, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
   resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Symporter</title>
  <%= stylesheet_link_tag    "application", media: "all", 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application.js', 'data-turbolinks-track' => true %>
 
  <script src="//code.jquery.com/jquery-1.7.1.min.js" ></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js" ></script>
 <link href='//fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
 <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
   <link href='//fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
      <style>
      h1 { font-family: 'Montserrat', serif; font-weight: 400; }
      h2 { font-family: 'Open Sans', serif; font-weight: 400; }
      h3 { font-family: 'Montserrat', serif; font-weight: 400; }
      h4 { font-family: 'Montserrat', serif; font-weight: 400; }
      h5 { font-family: 'Montserrat', serif; font-weight: 400; }
      h6 { font-family: 'Montserrat', serif; font-weight: 400; }
      p { font-family: 'Roboto', serif; font-weight: 400; }
      body { font-family: 'Roboto', serif; font-weight: 400; }
    </style>
 
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/images/favicon.ico">
  </head>
<body>

  <% flash.each do |message_type, message| %>
    
        <div class="alert alert-<%= message_type %>"><%= message %></div>
  
      <% end %>
   

<!-- NAVBAR ================================================== -->
  <div class="bannerContainer">
<nav class=" navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/" style="color=#1E90FF">SYMPORTER.</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

         
           <div class="navbar-header">
            <%= form_tag(products_path, :method => "get", id: "search-form") do %>
             <p>
                 <p>
                     <p>
                         <p>
            <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
  <%= submit_tag "Search", :name => nil %>
               </p>
             </p>
          </p>
        </p>
             </div>
          
          <% end %>
          
               <% if logged_in? %>
          <form class="navbar-form navbar-right">
            
            <div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    Account <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to "Profile", current_u %></li>
    <li><%= link_to "Settings", edit_u_path(current_u) %></li>
    <li><a href="/upload">Upload a new product</a></li>
    <li class="divider"></li>
    <li>
      <%= link_to "Log out", logout_path, method: "delete" %>
    </li>
  </ul>
</div>
          </form>
        <% else %>
    
               <form class="navbar-form navbar-right" FORM METHOD="LINK" ACTION="/login">
                 
            <div class="form-group">
            <button type="submit" class="btn">Sign in</button>
                 </div>
          </form>
                 <ul class="nav navbar-nav navbar-right">
            <li><a href="/signup"> Register </a></li>
          </ul>
             
        <% end %>
        </div>
      </div>
    </nav>
</div>
 
<%= yield %>

    <footer class="footer" >
      <div class="container">
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/about">Privacy</a></li>
        <li><a href="/contact">Terms</a></li>
        "<a href="https://commons.wikimedia.org/wiki/File:Depth_Coded_Phalloidin_Stained_Actin_Filaments_Cancer_Cell.png#/media/File:Depth_Coded_Phalloidin_Stained_Actin_Filaments_Cancer_Cell.png">Depth Coded Phalloidin Stained Actin Filaments Cancer Cell</a>" by <a href="//commons.wikimedia.org/wiki/User:Methylated603" title="User:Methylated603">Howard Vindin</a> - <span class="int-own-work" lang="en">Own work</span>. Licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0" title="Creative Commons Attribution-Share Alike 4.0">CC BY-SA 4.0</a> via <a href="//commons.wikimedia.org/wiki/">Wikimedia Commons</a>.
        <div>Icons made by <a href="http://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>             is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div>
      <p></p>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2015 Symporter, Un-Inc.
      </div>
  </footer>
      <%= debug(params) if Rails.env.development? %>



    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<%= javascript_include_tag "ie10-viewport-bug-workaround.js" %>
    <script src="ie10-viewport-bug-workaround.js"></script>
</body>
</html>